### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tuxarch** [Kylamber/Wireholecloud#1]
I registered where my passwords are marked and public IP in docker-compose.yml
docker compose up

[+] Running 5/5
 ✔ Network wireholecloud_private_network  Created                                                                                                                                                                                      0.2s 
 ✔ Container mariadb                      Created                                                                                                                                                                                      0.2s 
 ✔ Container pihole                       Created                                                                                                                                                                                      0.1s 
 ✔ Container wg-easy                      Created                                                                                                                                                                                      0.1s 
 ✔ Container nextcloud                    Created                                                                                                                                                                                      0.1s 
Attaching to mariadb, nextcloud, pihole, wg-easy
mariadb    | 2023-04-12 05:34:57+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.2+maria~ubu2204 started.
mariadb    | 2023-04-12 05:34:58+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb    | 2023-04-12 05:34:58+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.2+maria~ubu2204 started.
Error response from daemon: driver failed programming external connectivity on endpoint pihole (4115f3f0f7af8728db58b5b592eb32b96f8a94a3e7e3b5d171230474a57e5b69): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

**Comment by Kylamber** [comment]
Hi, judging from the error stating that 0.0.0.0:53 is already in use, is there another docker container running on the port 53 too? Since pihole requires the port 53 to function as a DNS.

If you could send out your `docker ps` output, maybe I could find out more about the issue.

**Comment by tuxarch** [comment]
sudo lsof -i :53
COMMAND   PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-r 302 systemd-resolve   19u  IPv4  15229      0t0  UDP _localdnsstub:domain 
systemd-r 302 systemd-resolve   20u  IPv4  15230      0t0  TCP _localdnsstub:domain (LISTEN)
systemd-r 302 systemd-resolve   21u  IPv4  15231      0t0  UDP _localdnsproxy:domain 
systemd-r 302 systemd-resolve   22u  IPv4  15232      0t0  TCP _localdnsproxy:domain (LISTEN)

**Comment by tuxarch** [comment]
Fixed it. In /etc/systemd/resolved.conf
DNS=1.1.1.1
DNSStubListener=no
reboot.
After that the container worked correctly.
